In [1]:
import numpy as np

In [2]:
my_array = [1,2,3,4]

In [3]:
type(my_array)

list

In [4]:
new_arr = np.array(my_array)

In [5]:
type(new_arr)

numpy.ndarray

In [6]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [10]:
np.zeros(shape = (4,4),dtype = int)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [11]:
np.ones(shape = (3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [15]:
np.random.seed(101)
arr = np.random.randint(0,100,10)
arr

array([95, 11, 81, 70, 63, 87, 75,  9, 77, 40])

In [16]:
arr1 = np.random.randint(0,101,10)

In [17]:
arr1

array([ 4, 63, 40, 60, 92, 64,  5, 12, 93, 40])

In [18]:
# To find maximum element
arr1.max()

93

In [19]:
# To find index of maximum element
arr1.argmax()

8

In [20]:
arr1.mean()

47.3

In [22]:
arr.shape

(10,)

In [24]:
arr.reshape((2,5))

array([[95, 11, 81, 70, 63],
       [87, 75,  9, 77, 40]])

In [25]:
matx = np.arange(0,100).reshape(10,10)

In [26]:
matx

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [27]:
row = 0
col = 1
matx[row,col]

1

In [28]:
# Grabbing all the items in a column
matx[:,1]

array([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [29]:
matx[:,1].reshape(10,1)

array([[ 1],
       [11],
       [21],
       [31],
       [41],
       [51],
       [61],
       [71],
       [81],
       [91]])

In [30]:
# For getting rows
matx[2,:]

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [32]:
matx[0:3,0:5]

array([[ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14],
       [20, 21, 22, 23, 24]])

In [33]:
new_matx = matx.copy()

In [40]:
new_matx[0:3,:] = 98 # Here : represents all the columns

In [39]:
new_matx

array([[98, 98, 98, 98, 98, 98, 98, 98, 98, 98],
       [98, 98, 98, 98, 98, 98, 98, 98, 98, 98],
       [98, 98, 98, 98, 98, 98, 98, 98, 98, 98],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])